spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/shopstyledb
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver